= Mesh

[overview]
----
difficulty 5
requires primitives/triangle
requires primitives/bounding-box-accelerator
reading primitives/mesh
----

preview::preview[]

== Implementation

This extension should be made by all team members, as each member can implement a different algorithm for building
bounding box hierarchies.

This extension consists of three steps:

* Reading the mesh.
* Optimizing the mesh.
* Writing the optimized mesh to file.

These steps are independent of the ray tracer. You should implement them as a separate tool, meaning
you should store the code in a separate directory in your repository.
You are also free to pick any programming language you wish to implement this extension.

In order to read a mesh, you need to have a mesh. For simplicity, you can use link:/meshes[any one of these meshes].
The format in which they're stored is described in the reading material.
If you feel like it, you can pick any other mesh you want.
An online source of freely downloadable meshes is http://archive3d.net/[Archive3D].
You will have to find out how to read in these files for yourself.
The `.ply` and `.obj` formats should be easy enough to process.

Once you've managed to read all triangles from the mesh, you can
start the optimization phase. We suggest working with a bounding box hierarchy,
as described in the reading material, but again you are free to take any approach you want.
The goal remains the same: being able to render a large mesh consisting of millions of
triangles in under a second.

Once the bounding box hierarchy has been built, you need to write it to file.
It is up to you to determine how to do this. Given the fact
that all team members are required to implement this extension,
it is advisable to use a common file format, so that
the ray tracer itself needs only be extended with one mesh loader.

[TASK]
====
Create a tool that builds bounding box hierarchies for meshes.
====
