// order 4
= Stratified - Half Jittered Sampler

[overview]
----
difficulty 2
reading samplers/basics
requires samplers/stratified-jittered
reading samplers/half-jittered
----

preview::preview[]

[TASK]
====
Implement the <</reference/samplers/half-jittered/explanations#,half-jittering sampler>>.
Make it public through a factory function

[source,language="c++"]
----
Sampler raytracer::samplers::stratified_half_jittered(unsigned rows, unsigned columns);
----
====

[TASK]
====
Expose the sampler to the scripting language by updating `scripting/samplers-module.cpp`.
====

== Evaluation

[TASK]
====
Render the scene below:

preview::challenge1[width="50%"]
====

[TASK]
====
Render the scene below:

preview::challenge2[width="50%"]
====

[TASK]
====
Write at least 10 tests that check cases easy to compute manually, such as

* Given a rectangle stem:[[0,1\]\times[0,1\]] and stem:[1 \times 1] samples, the returned sample should inside stem:[[0.25,0.75\]\times[0.25,0.75\]].
* Given a rectangle stem:[[0,2\]\times[0,1\]] and stem:[1 \times 1] samples, the returned sample should inside stem:[[0.5,1.5\]\times[0.25,0.75\]].
* Given a rectangle stem:[[0,1\]\times[0,2\]] and stem:[1 \times 1] samples, the returned sample should inside stem:[[0.25,0.75\]\times[0.5,1.5\]].
* Given a rectangle stem:[[5,2\]\times[8,6\]] and stem:[1 \times 1] samples, the returned sample should inside stem:[[6,7\]\times[3,5\]].
* Given a rectangle stem:[[0,8\]\times[0,8\]] and stem:[2 \times 2] samples, the returned samples should inside stem:[[1,3\]\times[1,3\]], stem:[[1,3\]\times[5,7\]], stem:[[5,7\]\times[1,3\]] and stem:[[5,7\]\times[5,7\]].

[IMPORTANT]
=====
The tests should not expect the samples to be returned in a certain order.
During the defense, this will be checked.
Failure to take this into account will disqualify this extension.
=====

[TIP]
=====
If you are uncertain of how to interpret the rectangle notation above (e.g., stem:[[0,4\]\times[0,4\]]), read <</reference/samplers/testing/explanations#,this page>>.
=====
====