// order 5

= Change Log

Welcome to my change log!
This is my very first one, so you _should_ feel honored.
Since many changes still need to be made, I decided to keep a log.

[NOTE,caption="21/11/21"]
====
Updated the <</extensions/math/transformations/explanations#,Transformations extension>>.
Its weight has been incremented.
====

[NOTE,caption="14/11/21"]
====
Updated the <</extensions/math/quaternions/explanations#,Quaternion extension>>.
It is a bit more work, but its weight has been increment as compensation.
====

[NOTE,caption="11/11/21"]
====
Completed the <</extensions/primitives/mesh/binary-mesh/explanations#,Binary Mesh Extension>>.
====

[NOTE,caption="10/11/21"]
====
Updated rules and minimal requirements.
====

[NOTE,caption="17/10/21"]
====
Added the <</extensions/samplers/comparison/explanations#,Sampler Comparison Extension>>.
====

[NOTE,caption="17/10/21"]
====
Added evaluation sections to sampler extensions.
====

[NOTE,caption="15/10/21"]
====
Finished <</extensions/renderers/edge/explanations#,Edge Renderer>>.
====

[NOTE,caption="11/10/21"]
====
Finished <</extensions/primitives/modifiers/grouper/explanations#,Grouper>>.
====

[NOTE,caption="11/10/21"]
====
Finished <</extensions/renderers/cartoon/explanations#,Cartoon Renderer>>.
====

[NOTE,caption="10/10/21"]
====
Added evaluation sections to ray tracer extensions.
====

[NOTE,caption="9/10/21"]
====
Added <</extensions/animations/wobble-easing/explanations#,wobble easing function>>.
====

[NOTE,caption="5/10/21"]
====
Updated mesh related pages.

* <</extensions/primitives/mesh/mesh-reader/explanations#,Mesh Primitive Extension>>
* <</extensions/primitives/mesh/mesh-optimizer/explanations#,Mesh Optimization Extension>>
* <</reference/primitives/mesh/basics/explanations#,Mesh Basics Explanations>>
* <</reference/primitives/mesh/optimizing/explanations#,Mesh Optimization Explanations>>
* <</reference/primitives/mesh/library/explanations#,Mesh Library>>
* <</reference/primitives/mesh/file-format/explanations#,Mesh File Format>>
* <</reference/primitives/mesh/mesh-reader/explanations#,Mesh Reader>>
====

[NOTE,caption="1/10/21"]
====
Updated <</extensions/cameras/depth-of-field/explanations#,Depth of Field Perspective Camera>>.
====

[NOTE,caption="1/10/21"]
====
Added GCC instructions.
====

[NOTE,caption="1/10/21"]
====
Aim&eacute;e's age has been incremented by one.
====

[NOTE,caption="29/9/21"]
====
Fixed some bugs in the ray tracer starter code.
Get updates using `git pull upstream master`.
====

[NOTE,caption="29/9/21"]
====
Fixed GitHub issues script.
More or less.
====

[NOTE,caption="27/9/21"]
====
Added note regarding GitHub issues.
====

[NOTE,caption="25/9/21"]
====
Added <</extensions/performance/balanced-parallel-task-scheduler/explanations#,Balanced Parallel Task Scheduler>>.
====

[NOTE,caption="25/9/21"]
====
Added <</extensions/performance/unbalanced-parallel-task-scheduler/explanations#,Unbalanced Parallel Task Scheduler>>.
====

[NOTE,caption="25/9/21"]
====
Added <</extensions/performance/naive-parallel-task-scheduler/explanations#,Naive Parallel Task Scheduler>>.
====

[NOTE,caption="25/9/21"]
====
Added <</reference/design/schedulers/explanations#,explanation of schedulers>>.
====

[NOTE,caption="24/9/21"]
====
Added "Rules" page.
====

[NOTE,caption="24/9/21"]
====
Updated Wif.Net viewer so that it uses a more recent version of AvalonEdit.

If you want to be able to enjoy whatever benefits it offers, do a `git pull` and recompile.
====

[NOTE,caption="24/9/21"]
====
Created this super fancy change log!
====
