// order 1
= Random Sampler

[overview]
----
difficulty 2
reading samplers/basics
reading samplers/random
reading samplers/testing
----

preview::preview[]

== Goal

The purpose of samplers is explained on the <</reference/design/concepts/explanations#,page discussing ray tracing concepts>>.
In short, we have a pixel for which we need to determine its color. We have to cast a ray through it which
we'll trace around the scene. But since the pixel is not a single point but is rectangular, there are infinitely
many points through which we could cast the ray.
A sampler's job is to pick points within the pixel. The number of points and which points these are is up to the sampler.
The only guarantee the sampler has to give is that when given a 2D rectangle, it will produce points
that are within this rectangle. Go take a look at ``samplers/sampler.h``. The (first) ``sample`` method reflects
this purpose: it takes a rectangle and returns a list of points. You can ignore the second ``sample`` overload for now.

The <</reference/samplers/random/explanations#,random sampler>> can be parameterized with an integer ``n``.
When asked to sample a rectangle, it will return ``n`` random points in this rectangle.

[TASK]
====
Create new files ``samplers/random-sampler.h`` and ``samplers/random-sampler.cpp``.
Define a new sampler class.
Let the existing ``single-sampler`` guide you.

[source,language="python"]
----
class RandomSampler(SamplerImplementation):
  # Constructor initializes fields
  def __init__(self, sample_count):
    self.__sample_count = sample_count
    # Create RNG once in constructor
    self.__random = Random()

  def sample(rectangle, callback):
    for _ in range(self.__sample_count):
      x = self.__random() # double between 0 and 1
      y = self.__random() # double between 0 and 1
      sample = rectangle.from_relative(x, y)

      callback(sample)


# Factory function takes a single parameter
def random_sampler(sample_count):
  return RandomSampler(sample_count)
----

[TIP]
=====
Use ``Rectangle2D::from_relative`` to easily find points inside the rectangle.
=====

[TIP]
=====
The `sample` method is `const`.
However, making use of the RNG changes its state.
In other words, your `const` method `sample` tries to change the state of one of the object's members, which is forbidden.
Luckily it's possible to https://en.cppreference.com/w/cpp/language/cv[circumvent the constness safely].
Do not dare use `const_cast` though, as this would lead to undefined behavior.
=====

[NOTE,caption="confession"]
=====
`sample` might actually be better off being a non``const`` method, but changing this at the time of writing would break students' code.
=====
====

[TASK]
====
Expose the sampler to the scripting language by updating `scripting/samplers-module.cpp`.
====

== Evaluation

[TASK]
====
Render the following scene:

preview::challenge1[width="50%"]

Explain why there is such noise on the circumference of the circle.
====

[TASK]
====
Render the following scene:

preview::challenge2[width="50%"]

Explain the change in noise.
What would you do to get rid of the noise altogether?
====
