// order 1
= Random Sampler

[overview]
----
difficulty 2
reading samplers/random
----

preview::preview[]

== Goal

The purpose of samplers is explained on the <</reference/design/concepts/explanations#,page discussing ray tracing concepts>>.
In short, we have a pixel for which we need to determine its color. We have to cast a ray through it which
we'll trace around the scene. But since the pixel is not a single point but is rectangular, there are infinitely
many points through which we could cast the ray.
A sampler's job is to pick points within the pixel. The number of points and which points these are is up to the sampler.
The only guarantee the sampler has to give is that when given a 2D rectangle, it will produce points
that are within this rectangle. Go take a look at ``samplers/sampler.h``. The (first) ``sample`` method reflects
this purpose: it takes a rectangle and returns a list of points. You can ignore the second ``sample`` overload for now.

The <</reference/samplers/random/explanations#,random sampler>> can be parameterized with an integer ``n``.
When asked to sample a rectangle, it will return ``n`` random points in this rectangle.

[TASK]
====
Create new files ``samplers/random-sampler.h`` and ``samplers/random-sampler.cpp``.
Define a new sampler class (let the existing ``single-sampler`` guide you.)

* ``RandomSampler`` should have a field ``m_sample_count`` which can be initialized using the constructor.
* The factory function ``raytracer::samplers::random`` should accept a single integer parameter ``sample_count``
  and use it to create a new ``RandomSampler``.
* For this extension, you need only override the ``sample`` overload that returns a list of points.
  Implement it so that it picks ``m_sample_count`` random points inside the rectangle.
  Use a <a href="http://en.cppreference.com/w/cpp/numeric/random/uniform_real_distribution">uniform distribution</a>.
  You might want to rely on ``Rectangle2D::from_relative`` to easily find points inside the rectangle.
====

== Evaluation

TODO
