= Parallel Task Scheduler

[overview]
----
difficulty 3
reading design/wrappers
----

== Concepts

=== Tasks

In order to facilitate the implementation of a multithreaded ray tracer, we introduced
the concept of <em>tasks</em>. A task is an independent unit of work. Two tasks
should be able to be performed in any order without it affecting the results.

Tasks are modelled by the ``Task`` class, declared in ``tasks/tasks.h``.
This class defines a single method ``perform``.

=== Task Schedulers

A <em>task scheduler</em> takes a list of tasks and performs each of them.
No guarantees are made about the order in which it performs them.

Task schedulers are modelled by the ``TaskSchedulerImplementation``
(and <%= link 'reference/design/wrappers', 'wrapped' %> by ``TaskScheduler``s.
They only provide one method: ``perform``, which takes a list of tasks.

=== Serial Task Scheduler

You were given ``SerialTaskScheduler``, a task scheduler
that performs the tasks in sequential order. Take a look at the code
in ``tasks/serial-task-scheduler.cpp``: you'll see that
it is nothing but a loop.

=== Parallel Task Scheduler

The purpose of this extension is to implement ``ParallelTaskScheduler``.
Its ``perform`` method should create multiple threads and
divide the tasks among them.

[TASK]
====
Implement ``ParallelTaskScheduler``. It needs to give the following guarantees:

* All given tasks must be performed exactly once.
* The scheduler's ``perform`` method returns only after all tasks have been performed.

Since the tasks are independent, you do not need to perform any synchronization on their behalf.
A class that might come in handy is <a href="http://en.cppreference.com/w/cpp/atomic/atomic">atomic</a>,
but many other approaches are possible too.
====
