// order 2
= Stratified Sampler

[overview]
----
difficulty 2
reading samplers/basics
reading samplers/stratified
reading samplers/testing
----

preview::preview[]

== Implementation

[TASK]
====
Implement the <</reference/samplers/stratified/explanations#,stratified sampler>>.
Make it public through a factory function

[source,language="c++"]
----
Sampler raytracer::samplers::stratified_fixed(unsigned rows, unsigned columns);
----

[TIP]
=====
You can use the ``math::Rasterizer`` class to subdivide the rectangle into subrectangles.
=====
====

[TASK]
====
Expose the sampler to the scripting language by updating `scripting/samplers-module.cpp`.
====

== Evaluation

[TASK]
====
Render the scene below:

preview::challenge1[width="50%"]
====

[TASK]
====
Render the scene below:

preview::challenge2[width="50%"]
====

[TASK]
====
Write at least 10 tests that check cases easy to compute manually, such as

* Given a rectangle stem:[[0,1\]\times[0,1\]] and stem:[1 \times 1] samples, the returned sample should be stem:[\{ (0.5, 0.5) \}].
* Given a rectangle stem:[[5,7\]\times[3,7\]] and stem:[1 \times 1] samples, the returned sample should be stem:[\{ (6, 5) \}].
* Given a rectangle stem:[[0,2\]\times[0,2\]] and stem:[1 \times 1] samples, the returned sample should be stem:[\{ (1, 1) \}].
* Given a rectangle stem:[[0,4\]\times[0,2\]] and stem:[2 \times 1] samples, the returned samples should be stem:[\{ (1, 1), (3, 1) \}].
* Given a rectangle stem:[[0,2\]\times[0,4\]] and stem:[1 \times 2] samples, the returned samples should be stem:[\{ (1, 1), (1, 3) \}].
* Given a rectangle stem:[[0,4\]\times[0,4\]] and stem:[4 \times 4] samples, the returned samples should be stem:[\{ (i + 0.5, j + 0.5) \;|\; i = 0\dots3, j=0\dots3 \}].

[IMPORTANT]
=====
The tests should not expect the samples to be returned in a certain order.
During the defense, this will be checked.
Failure to take this into account will disqualify this extension.
=====

[TIP]
=====
If you are uncertain of how to interpret the rectangle notation above (e.g., stem:[[0,4\]\times[0,4\]]), read <</reference/samplers/testing/explanations#,this page>>.
=====

[TIP]
=====
See the reading material if you have no clue about how to write sampler tests.
=====
====
