= 3D Material Transformer

[overview]
----
reading materials/2d-vs-3d
----

== Implementation

[WARNING]
====
Note: before you implement this extension, you need to have at least implemented some kind of 3D material, otherwise 3D material transformations will be useless.
====

Material transformers should not be confused with primitive transformers.
Primitive transformers change the shape of primitives, i.e. they scale, move and rotate 3D objects.
Material transformers only transform the materials themselves.
Examples of 3D transformations can be found on

* <<extensions/materials/scaling3d#,scale3d>>
* <<extensions/materials/translation3d#,translate3d>>
* <<extensions/materials/rotation3d#,rotate3d>>

For this extension, you will implement the ``Material3DTransformer``.
It is able to perform arbitrary transformations on 3D materials.
The <<extensions/materials/scaling3d#,scale3d>>, <<extensions/materials/translation3d#,translate3d>>, <<extensions/materials/rotation3d#,rotate3d>> and  extensions will build upon this class.

[TASK]
====
Implement ``Material3DTransformer``.

* A ``Material3DTransformer`` is a subclass of ``MaterialImplementation``.
  It is parameterized by a child ``Material`` (the one that is being transformed) and a ``Transformation3D``.
* You will need to override the ``at`` member function.
  You will have to find out for yourself what should happen here.
====
