// order 5
= N-Rooks Sampler

[overview]
----
difficulty 3
reading samplers/basics
reading samplers/nrooks
----

preview::preview[]


[TASK]
====
Implement the <</reference/samplers/nrooks/explanations#,n-rooks sampler>>.
Make it public through a factory function

[source,language="c++"]
----
Sampler raytracer::samplers::nrooks(unsigned sample_count);
----
====

[TASK]
====
Expose the sampler to the scripting language by updating `scripting/samplers-module.cpp`.
====

== Evaluation

[TASK]
====
Render the scene below:

preview::challenge1[width="50%"]
====

[TASK]
====
Render the scene below:

preview::challenge2[width="50%"]
====

[TASK]
====
Write at least 5 tests that check cases easy to compute manually, such as

* Given a rectangle stem:[[0,1\]\times[0,1\]] and stem:[N=1] sample, the returned sample should inside stem:[[0,1\]\times[0,1\]].
* Given a rectangle stem:[[4,8\]\times[6,7\]] and stem:[N=1] sample, the returned sample should inside stem:[[4,8\]\times[6,7\]].
* Given a rectangle stem:[[0,4\]\times[0,4\]] and stem:[N=4] samples,
** 4 samples should be returned.
** One sample should have its x-coordinate in stem:[[0, 1\]].
** One sample should have its x-coordinate in stem:[[1, 2\]].
** One sample should have its x-coordinate in stem:[[2, 3\]].
** One sample should have its x-coordinate in stem:[[3, 4\]].
** One sample should have its y-coordinate in stem:[[0, 1\]].
** One sample should have its y-coordinate in stem:[[1, 2\]].
** One sample should have its y-coordinate in stem:[[2, 3\]].
** One sample should have its y-coordinate in stem:[[3, 4\]].

[IMPORTANT]
=====
The tests should not expect the samples to be returned in a certain order.
During the defense, this will be checked.
Failure to take this into account will disqualify this extension.
=====

[TIP]
=====
If you are uncertain of how to interpret the rectangle notation above (e.g., stem:[[0,4\]\times[0,4\]]), read <</reference/samplers/testing/explanations#,this page>>.
=====
====
